scrape_configs:

  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: celery
    scrape_interval: 5s
    static_configs:
    - targets: ['10.0.0.13:9808']

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] 